export enum Status {
  PENDIENTE = 'PENDIENTE',
  ADOPTADO = 'ADOPTADO',
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  ELIMINADO = 'ELIMINADO',
  PAUSADO = 'PAUSADO',
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO',
  CANCELADO = 'CANCELADO',
  ENVIADO = 'ENVIADO',
  LEIDO = 'LEIDO',

    //PARA LOGROS
  EXPIRADO = 'EXPIRADO',
  EN_PROGRESO = 'EN_PROGRESO',
  COMPLETADO = 'COMPLETADO'
}