export enum Status {
  PENDIENTE = 'PENDIENTE',
  ADOPTADO = 'ADOPTADO',
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  ELIMINADO = 'ELIMINADO',
  PAUSADO = 'PAUSADO',

  // --- AÑADIR ESTOS ESTADOS ---
  // (Estados para AdoptionRequest)
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO',
  CANCELADO = 'CANCELADO'
}